# Generated by Django 4.2.3 on 2023-07-09 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_event_ahmad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Event_ahmad',
        ),
        migrations.DeleteModel(
            name='Eventt',
        ),
    ]
