# Generated by Django 4.2.3 on 2023-07-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_delete_event_delete_event_ahmad_delete_eventt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('data', models.JSONField()),
            ],
        ),
    ]
