# Generated by Django 4.2.3 on 2023-07-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0009_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
