# Generated by Django 4.2.3 on 2023-07-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0012_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=255)),
                ('flight_number', models.CharField(max_length=255)),
                ('departure_airport_code', models.CharField(max_length=10)),
                ('departure_airport_name', models.CharField(max_length=255)),
                ('departure_latitude', models.FloatField()),
                ('departure_longitude', models.FloatField()),
                ('arrival_airport_code', models.CharField(max_length=10)),
                ('arrival_airport_name', models.CharField(max_length=255)),
                ('arrival_latitude', models.FloatField()),
                ('arrival_longitude', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.event')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='things.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Thing',
        ),
    ]
